# ---------- Paths ----------
paths:
  # Path to thumbnail features (trainset)
  thumb_train: "fivr_thumbs.npy"
  # Path to thumbnail features (testset)
  thumb_test: "fivr_thumbs_test.npy"
  # Path to fisher vector features (trainset)
  fv_train: "fivr_fv.npy"
  # Path to fisher vector features (testset)
  fv_test: "fivr_fv_test.npy"
  # Path to VGG features (trainset)
  vgg_train: "fivr_vgg.npy"
  # Path to VGG features (testset)
  vgg_test: "fivr_vgg_test.npy"
  # Path to output folder
  out_path: "output/"

# ---------- KD-Tree Parameters ----------
kdtree:
  #  k value for k-NN
  k: 64
  # Leafsize for KD-Tree
  leafsize: 32

# ---------- PCA Parameters ----------
pca:
  # PCA components for thumbnail features
  thumb_components: 32
  # PCA components for fisher vector features
  fv_components: 32
  # PCA components for VGG features
  vgg_components: 32
  # Number of train samples for PCA (150000 for FIVR-200K and 200000 for VCSL Dataset)
  train_samples: 150000
  # True for saving the trained PCA model and False for not saving
  save_pca: False
