# Path to k-d Trees (generated via 'build_repo.py')
repo_kdtrees: 'tree_data.pkl'

# Path to PCA projected thumbnail features (testset) (generated via 'build_test_repo.py')
repo_thumb_test: "thumb_repo_test.npy"

# Path to PCA projected fisher vector features (testset) (generated via 'build_test_repo.py')
repo_fv_test: "fv_repo_test.npy"

# Path to PCA projected VGG features (testset) (generated via 'build_test_repo.py')
repo_vgg_test: "vgg_repo_test.npy"

# Path to indexes file (.npy) (generated via 'gen_index_file.py')
repo_indexes: "indx.pickle"

# Path to test indexes file (.npy) (generated via 'gen_index_file.py')
repo_indexes_test: "indx_test.pickle"

# Path to output folder
out_path: "output/"

# Time step used while generating test query. This is the ts you used while running 'build_test_repo.py'
ts: 10.0

# Tolerance while pruning timestamps
tolerance: 1.5

# List of k values to use while querying the k-d trees.
# k = number of neighbors to return while querying the k-d tree.
k_values: [64, 128, 256, 512]

# List of timestamp thresholds to use while calculating timestamp accuracy
acc_ts_th: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 10.0, 15.0]

# Frame sampling interval in seconds. This is the frame_interval you used while running 'extract_frames.py'
# 0.5 (extracts 1 frame every 0.5 seconds).
# 30 -> extracts 1 frame every 30 seconds.
frame_interval: 0.5

